Repository RedHatInsights/vmaas, pull requests merged in 2022-01, with the labels that each got.

#943 chore: remove legacy service objects
  deploy/clowdapp.yaml
Labels: skip-tests

#947 chore(gh-actions): delete integration-tests-local
  .github/workflows/ci.yml
Labels: skip-deploy

#948 chore(pr_check): always create artifacts dir
  pr_check.sh
Labels: skip-build
